# ===========================
# Stage 1: Build
# ===========================
FROM node:22-alpine AS build
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY . .
RUN npm run build -- --configuration=production

# ===========================
# Stage 2: Serve com Nginx
# ===========================
FROM nginx:alpine
COPY --from=build /app/dist/app-compras-frontend/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
